import type { CollectionConfig } from 'payload'

export const Destinations: CollectionConfig = {
  slug: 'destinations',
  admin: {
    useAsTitle: 'name',
  },
  access: {
    read: () => true,
    create: ({ req }) => req.user?.role === 'admin' || req.user?.role === 'editor',
    update: ({ req }) => req.user?.role === 'admin' || req.user?.role === 'editor',
    delete: ({ req }) => req.user?.role === 'admin',
  },
  fields: [
    {
      name: 'name',
      type: 'text',
      required: true,
    },
    {
      name: 'slug',
      type: 'text',
      required: true,
      unique: true,
    },
    {
      name: 'description',
      type: 'textarea',
    },
    {
      name: 'coverImage',
      type: 'upload',
      relationTo: 'media',
    },
    {
      name: 'country',
      type: 'text',
    },
    {
      name: 'region',
      type: 'select',
      options: [
        { label: 'Asia', value: 'asia' },
        { label: 'Europe', value: 'europe' },
        { label: 'Middle East', value: 'middle-east' },
        { label: 'USA', value: 'usa' },
        { label: 'Africa', value: 'africa' },
        { label: 'Australia & Oceania', value: 'australia' },
        { label: 'South America', value: 'south-america' },
        { label: 'North America', value: 'north-america' },
      ],
    },
    {
      name: 'activities',
      type: 'array',
      fields: [
        {
          name: 'activity',
          type: 'select',
          options: [
            { label: 'Hiking', value: 'hiking' },
            { label: 'Honeymoon', value: 'honeymoon' },
            { label: 'Backpacking', value: 'backpacking' },
            { label: 'Solo Travel', value: 'solo-travel' },
            { label: 'Group Travel', value: 'group-travel' },
            { label: 'Food & Culinary', value: 'food' },
            { label: 'Culture & Heritage', value: 'culture' },
            { label: 'Adventure', value: 'adventure' },
            { label: 'Beach & Relaxation', value: 'beach' },
            { label: 'Wildlife & Nature', value: 'wildlife' },
          ],
        },
      ],
    },
    {
      name: 'worldRanking',
      type: 'number',
      min: 1,
      max: 100,
      admin: {
        description: 'UNWTO World Tourism Ranking position',
      },
    },
    {
      name: 'tourismScore',
      type: 'number',
      min: 0,
      max: 100,
    },
    {
      name: 'isTrending',
      type: 'checkbox',
      defaultValue: false,
    },
    {
      name: 'bestTimeToVisit',
      type: 'text',
    },
    {
      name: 'offbeatGems',
      type: 'textarea',
      admin: {
        description: 'Hidden gems and offbeat places to beat the crowd',
      },
    },
    {
      name: 'featured',
      type: 'checkbox',
      defaultValue: false,
    },
    {
      name: 'richContent',
      type: 'textarea',
      admin: {
        description: 'Rich HTML content for the destination detail page (generated by AI or hand-written)',
        rows: 20,
      },
    },
  ],
}
